# Generated by Django 3.0.2 on 2020-04-22 00:13

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 22, 0, 13, 32, 812463))),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('code', models.CharField(default='NULL', max_length=20)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('product_type', models.CharField(max_length=50)),
                ('long_description', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=300)),
                ('available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('ranking', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 22, 0, 13, 32, 813048))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 4, 22, 0, 13, 32, 813065))),
                ('front_image', models.ImageField(upload_to='Online_Shop/')),
                ('product_id', models.ForeignKey(default='NULL', on_delete=django.db.models.deletion.DO_NOTHING, to='product.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Products')),
            ],
        ),
        migrations.CreateModel(
            name='product_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_image', models.ImageField(upload_to='Online_Shop/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Products')),
            ],
        ),
        migrations.CreateModel(
            name='Sale_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_name', models.CharField(default='NULL', max_length=20)),
                ('sale_percentage', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('locations', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.Locations')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
                ('sale_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Sale')),
            ],
            options={
                'unique_together': {('sale_id', 'product_id')},
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Locations')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Products')),
            ],
            options={
                'unique_together': {('product_id', 'location')},
            },
        ),
    ]
